noun = input("Input a Noun: ")
print("There once was a teenager who was walking into the woods where she like to find " + noun )
verb = input("Input a Verb: ")
print("While she was looking for " + noun + "she started to hear some strange noises so she " + verb)
adjective = input("Input a Adjective: ")
print("When she " + verb + " she crashed into a " + adjective + "boy who was also walking into the woods.")
name = input("Input a Name: ")
print("The " + adjective + "boy introduced himself and said his name was " + name + ".")
print("When the " + adjective + "boy introduced himself he and the teenage girl felt that she was okay now and he helped her find " + noun + ".")
print(" When they were looking for her " + noun + " they saw they had many things in common then out of knowwhere there was a weird sound. They went toward the sound and they finally found her " + noun + ".")
response = input ("Input a Response: ")
print("The boy walked the girl home and and then asked her if he can see her again and she said " + response + "."  )
print("To be continued...")